from django.core.management.base import BaseCommand
from library_app.models import LibraryLocation


class Command(BaseCommand):
    help = "Seed dữ liệu thư viện toàn quốc Việt Nam"

    def handle(self, *args, **kwargs):
        libraries = [
            {
                "name": "Thư viện Quốc gia Việt Nam",
                "province": "Hà Nội",
                "address": "31 Tràng Thi, Hoàn Kiếm, Hà Nội",
                "latitude": 21.028511,
                "longitude": 105.804817,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện quốc gia trung tâm.",
                "is_active": True,
            },
            {
                "name": "Thư viện Hà Nội",
                "province": "Hà Nội",
                "address": "47 Bà Triệu, Hoàn Kiếm, Hà Nội",
                "latitude": 21.020976,
                "longitude": 105.850258,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện công cộng của thành phố Hà Nội.",
                "is_active": True,
            },
            {
                "name": "Thư viện Tạ Quang Bửu",
                "province": "Hà Nội",
                "address": "Đại học Bách khoa Hà Nội, Hai Bà Trưng, Hà Nội",
                "latitude": 21.006345,
                "longitude": 105.843186,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 20:30",
                "description": "Trung tâm học liệu của Đại học Bách khoa Hà Nội.",
                "is_active": True,
            },
            {
                "name": "Thư viện Đại học Quốc gia Hà Nội",
                "province": "Hà Nội",
                "address": "144 Xuân Thủy, Cầu Giấy, Hà Nội",
                "latitude": 21.036785,
                "longitude": 105.782438,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:30",
                "description": "Trung tâm thông tin - thư viện Đại học Quốc gia Hà Nội.",
                "is_active": True,
            },
            {
                "name": "Thư viện Đại học Quốc gia TP.HCM",
                "province": "TP.HCM",
                "address": "Khu đô thị ĐHQG TP.HCM, Thủ Đức, TP.HCM",
                "latitude": 10.879983,
                "longitude": 106.805359,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 20:00",
                "description": "Trung tâm thông tin - thư viện ĐHQG TP.HCM.",
                "is_active": True,
            },
            {
                "name": "Thư viện Đại học Khoa học Tự nhiên TP.HCM",
                "province": "TP.HCM",
                "address": "227 Nguyễn Văn Cừ, Quận 5, TP.HCM",
                "latitude": 10.762622,
                "longitude": 106.682171,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện phục vụ sinh viên và giảng viên.",
                "is_active": True,
            },
            {
                "name": "Thư viện Tổng hợp Đà Nẵng",
                "province": "Đà Nẵng",
                "address": "46 Bạch Đằng, Hải Châu, Đà Nẵng",
                "latitude": 16.067780,
                "longitude": 108.220830,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng lớn của thành phố Đà Nẵng.",
                "is_active": True,
            },
            {
                "name": "Trung tâm Học liệu Đại học Đà Nẵng",
                "province": "Đà Nẵng",
                "address": "41 Lê Duẩn, Hải Châu, Đà Nẵng",
                "latitude": 16.075247,
                "longitude": 108.217696,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 20:00",
                "description": "Trung tâm học liệu phục vụ Đại học Đà Nẵng.",
                "is_active": True,
            },
            {
                "name": "Thư viện Tổng hợp Thừa Thiên Huế",
                "province": "Thừa Thiên Huế",
                "address": "29A Lê Quý Đôn, Huế",
                "latitude": 16.463713,
                "longitude": 107.590866,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng của tỉnh Thừa Thiên Huế.",
                "is_active": True,
            },
            {
                "name": "Trung tâm Học liệu Đại học Huế",
                "province": "Thừa Thiên Huế",
                "address": "20 Lê Lợi, Huế",
                "latitude": 16.466016,
                "longitude": 107.593421,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 20:00",
                "description": "Trung tâm học liệu phục vụ Đại học Huế.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Nghệ An",
                "province": "Nghệ An",
                "address": "Vinh, Nghệ An",
                "latitude": 18.679585,
                "longitude": 105.681335,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Nghệ An.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Thanh Hóa",
                "province": "Thanh Hóa",
                "address": "TP. Thanh Hóa, Thanh Hóa",
                "latitude": 19.807692,
                "longitude": 105.776221,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Thanh Hóa.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Quảng Ninh",
                "province": "Quảng Ninh",
                "address": "Hạ Long, Quảng Ninh",
                "latitude": 20.971197,
                "longitude": 107.044806,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Quảng Ninh.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Hải Phòng",
                "province": "Hải Phòng",
                "address": "Hồng Bàng, Hải Phòng",
                "latitude": 20.844911,
                "longitude": 106.688084,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng thành phố Hải Phòng.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Bắc Ninh",
                "province": "Bắc Ninh",
                "address": "TP. Bắc Ninh, Bắc Ninh",
                "latitude": 21.186083,
                "longitude": 106.076313,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Bắc Ninh.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Lào Cai",
                "province": "Lào Cai",
                "address": "TP. Lào Cai, Lào Cai",
                "latitude": 22.485560,
                "longitude": 103.970660,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Lào Cai.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Thái Nguyên",
                "province": "Thái Nguyên",
                "address": "TP. Thái Nguyên, Thái Nguyên",
                "latitude": 21.594222,
                "longitude": 105.848170,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Thái Nguyên.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Khánh Hòa",
                "province": "Khánh Hòa",
                "address": "Nha Trang, Khánh Hòa",
                "latitude": 12.238791,
                "longitude": 109.196749,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Khánh Hòa.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Lâm Đồng",
                "province": "Lâm Đồng",
                "address": "Đà Lạt, Lâm Đồng",
                "latitude": 11.940419,
                "longitude": 108.458313,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Lâm Đồng.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Bình Dương",
                "province": "Bình Dương",
                "address": "Thủ Dầu Một, Bình Dương",
                "latitude": 10.980460,
                "longitude": 106.651856,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Bình Dương.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Đồng Nai",
                "province": "Đồng Nai",
                "address": "Biên Hòa, Đồng Nai",
                "latitude": 10.944690,
                "longitude": 106.824318,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Đồng Nai.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Bà Rịa - Vũng Tàu",
                "province": "Bà Rịa - Vũng Tàu",
                "address": "Vũng Tàu, Bà Rịa - Vũng Tàu",
                "latitude": 10.411379,
                "longitude": 107.136224,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Bà Rịa - Vũng Tàu.",
                "is_active": True,
            },
            {
                "name": "Thư viện TP Cần Thơ",
                "province": "Cần Thơ",
                "address": "Ninh Kiều, Cần Thơ",
                "latitude": 10.045162,
                "longitude": 105.746857,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện công cộng thành phố Cần Thơ.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh An Giang",
                "province": "An Giang",
                "address": "Long Xuyên, An Giang",
                "latitude": 10.386389,
                "longitude": 105.435181,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh An Giang.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Kiên Giang",
                "province": "Kiên Giang",
                "address": "Rạch Giá, Kiên Giang",
                "latitude": 10.012450,
                "longitude": 105.080910,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Kiên Giang.",
                "is_active": True,
            },
            {
                "name": "Thư viện tỉnh Cà Mau",
                "province": "Cà Mau",
                "address": "TP. Cà Mau, Cà Mau",
                "latitude": 9.176820,
                "longitude": 105.152420,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng tỉnh Cà Mau.",
                "is_active": True,
            },
            {
                "name": "Thư viện Khoa học Tổng hợp TP.HCM",
                "province": "TP.HCM",
                "address": "69 Lý Tự Trọng, Quận 1",
                "latitude": 10.776889,
                "longitude": 106.700806,
                "phone": "",
                "website": "",
                "open_time": "07:30 - 17:00",
                "description": "Thư viện công cộng lớn nhất TP.HCM",
                "is_active": True,
            },
            {
                "name": "Thư viện Quận 1",
                "province": "TP.HCM",
                "address": "Quận 1, TP.HCM",
                "latitude": 10.776500,
                "longitude": 106.701000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Quận 1.",
                "is_active": True,
            },
            {
                "name": "Không gian sách Nguyễn Huệ",
                "province": "TP.HCM",
                "address": "Đường Nguyễn Huệ, Quận 1, TP.HCM",
                "latitude": 10.774500,
                "longitude": 106.703000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Không gian đọc sách và hoạt động văn hóa đọc tại trung tâm thành phố.",
                "is_active": True,
            },
            {
                "name": "Thư viện Quận 3",
                "province": "TP.HCM",
                "address": "Quận 3, TP.HCM",
                "latitude": 10.784000,
                "longitude": 106.688000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Quận 3.",
                "is_active": True,
            },
            {
                "name": "Thư viện Quận 5",
                "province": "TP.HCM",
                "address": "Quận 5, TP.HCM",
                "latitude": 10.755000,
                "longitude": 106.667000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Quận 5.",
                "is_active": True,
            },
            {
                "name": "Thư viện Quận 7",
                "province": "TP.HCM",
                "address": "Quận 7, TP.HCM",
                "latitude": 10.729000,
                "longitude": 106.721000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Quận 7.",
                "is_active": True,
            },
            {
                "name": "Thư viện Quận 10",
                "province": "TP.HCM",
                "address": "Quận 10, TP.HCM",
                "latitude": 10.772000,
                "longitude": 106.667000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Quận 10.",
                "is_active": True,
            },
            {
                "name": "Thư viện Tân Bình",
                "province": "TP.HCM",
                "address": "Quận Tân Bình, TP.HCM",
                "latitude": 10.801000,
                "longitude": 106.652000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Tân Bình.",
                "is_active": True,
            },
            {
                "name": "Thư viện Gò Vấp",
                "province": "TP.HCM",
                "address": "Quận Gò Vấp, TP.HCM",
                "latitude": 10.838000,
                "longitude": 106.665000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Gò Vấp.",
                "is_active": True,
            },
            {
                "name": "Thư viện Phú Nhuận",
                "province": "TP.HCM",
                "address": "Quận Phú Nhuận, TP.HCM",
                "latitude": 10.800500,
                "longitude": 106.682000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Phú Nhuận.",
                "is_active": True,
            },
            {
                "name": "Thư viện TP Thủ Đức",
                "province": "TP.HCM",
                "address": "TP Thủ Đức, TP.HCM",
                "latitude": 10.849000,
                "longitude": 106.771000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực TP Thủ Đức.",
                "is_active": True,
            },
            {
                "name": "Thư viện Bình Thạnh",
                "province": "TP.HCM",
                "address": "Quận Bình Thạnh, TP.HCM",
                "latitude": 10.810000,
                "longitude": 106.709000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Bình Thạnh.",
                "is_active": True,
            },
            {
                "name": "Thư viện Tân Phú",
                "province": "TP.HCM",
                "address": "Quận Tân Phú, TP.HCM",
                "latitude": 10.791000,
                "longitude": 106.620000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Tân Phú.",
                "is_active": True,
            },
            {
                "name": "Thư viện Bình Tân",
                "province": "TP.HCM",
                "address": "Quận Bình Tân, TP.HCM",
                "latitude": 10.765000,
                "longitude": 106.600000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Bình Tân.",
                "is_active": True,
            },
            {
                "name": "Thư viện Hóc Môn",
                "province": "TP.HCM",
                "address": "Huyện Hóc Môn, TP.HCM",
                "latitude": 10.890000,
                "longitude": 106.590000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Hóc Môn.",
                "is_active": True,
            },
            {
                "name": "Thư viện Củ Chi",
                "province": "TP.HCM",
                "address": "Huyện Củ Chi, TP.HCM",
                "latitude": 11.000000,
                "longitude": 106.500000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Củ Chi.",
                "is_active": True,
            },
            {
                "name": "Thư viện Nhà Bè",
                "province": "TP.HCM",
                "address": "Huyện Nhà Bè, TP.HCM",
                "latitude": 10.690000,
                "longitude": 106.730000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Nhà Bè.",
                "is_active": True,
            },
            {
                "name": "Thư viện Cần Giờ",
                "province": "TP.HCM",
                "address": "Huyện Cần Giờ, TP.HCM",
                "latitude": 10.411000,
                "longitude": 106.954000,
                "phone": "",
                "website": "",
                "open_time": "08:00 - 17:00",
                "description": "Thư viện phục vụ bạn đọc tại khu vực Cần Giờ.",
                "is_active": True,
            },
        ]

        created_count = 0
        updated_count = 0

        for item in libraries:
            obj, created = LibraryLocation.objects.update_or_create(
                name=item["name"], province=item["province"], defaults=item
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seed hoàn tất: tạo mới {created_count}, cập nhật {updated_count} thư viện."
            )
        )
