# Generated by Django 6.0.2 on 2026-03-28 18:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=300, verbose_name='Tên sách')),
                ('author', models.CharField(max_length=200, verbose_name='Tác giả')),
                ('publisher', models.CharField(max_length=200, verbose_name='NXB')),
                ('publish_year', models.IntegerField(verbose_name='Năm xuất bản')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='Tổng số bản')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Sách có sẵn')),
                ('language', models.CharField(default='Tiếng Việt', max_length=50)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Kho sách',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#1e6fbf', max_length=7)),
                ('icon', models.CharField(default='book', max_length=50)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục sách',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Ma the')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ho ten')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nu'), ('O', 'Khac')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(verbose_name='Ngay sinh')),
                ('phone', models.CharField(max_length=15, verbose_name='So dien thoai')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Dia chi')),
                ('card_issue_date', models.DateField(default=django.utils.timezone.now)),
                ('card_expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Hoat dong'), ('suspended', 'Tam khoa'), ('expired', 'Het han')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='readers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doc gia',
                'verbose_name_plural': 'Doc gia',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('borrow_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngay muon')),
                ('due_date', models.DateField(verbose_name='Han tra')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Ngay tra')),
                ('status', models.CharField(choices=[('borrowed', 'Dang muon'), ('returned', 'Da tra'), ('overdue', 'Qua han'), ('lost', 'Mat sach')], default='borrowed', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='library_app.book')),
                ('librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_borrows', to=settings.AUTH_USER_MODEL)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='library_app.reader')),
            ],
            options={
                'verbose_name': 'Phieu muon',
                'verbose_name_plural': 'Phieu muon/tra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='library_app.category'),
        ),
        migrations.CreateModel(
            name='FinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Tien mat'), ('transfer', 'Chuyen khoan'), ('card', 'The ngan hang')], default='cash', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('borrow_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='library_app.borrowrecord')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thanh toan phat',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('overdue', 'Qua han tra'), ('due_soon', 'Sap den han'), ('fine', 'Phi phat'), ('system', 'He thong')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrow_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.borrowrecord')),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='library_app.reader')),
            ],
            options={
                'verbose_name': 'Thong bao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Cho sach'), ('ready', 'San sang lay'), ('cancelled', 'Da huy'), ('fulfilled', 'Hoan thanh')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='library_app.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='library_app.reader')),
            ],
            options={
                'verbose_name': 'Dat truoc sach',
                'ordering': ['-reserved_at'],
            },
        ),
    ]
