# Generated by Django 6.0.3 on 2026-04-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='reader',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('suspended', 'Tạm Khóa'), ('expired', 'Hết hạn')], default='active', max_length=20),
        ),
    ]
