# Generated by Django 6.0.3 on 2026-04-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_reader_gender_alter_reader_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thư viện')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('open_time', models.CharField(blank=True, max_length=100, verbose_name='Giờ mở cửa')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thư viện',
                'verbose_name_plural': 'Thư viện toàn quốc',
                'ordering': ['province', 'name'],
            },
        ),
    ]
