# Generated by Django 6.0.3 on 2026-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_reader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_page_1',
            field=models.ImageField(blank=True, null=True, upload_to='book_previews/', verbose_name='Trang xem trước 1'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_page_2',
            field=models.ImageField(blank=True, null=True, upload_to='book_previews/', verbose_name='Trang xem trước 2'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_page_3',
            field=models.ImageField(blank=True, null=True, upload_to='book_previews/', verbose_name='Trang xem trước 3'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_page_4',
            field=models.ImageField(blank=True, null=True, upload_to='book_previews/', verbose_name='Trang xem trước 4'),
        ),
        migrations.AddField(
            model_name='librarylocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='libraries/', verbose_name='Hình ảnh'),
        ),
    ]
