# Generated by Django 6.0.3 on 2026-04-08 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_book_preview_page_1_book_preview_page_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên chi nhánh')),
                ('address', models.TextField(verbose_name='Địa chỉ chi nhánh')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('open_time', models.CharField(blank=True, max_length=100, verbose_name='Giờ mở cửa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='library_app.librarylocation', verbose_name='Thư viện chính')),
            ],
            options={
                'verbose_name': 'Chi nhánh thư viện',
                'verbose_name_plural': 'Chi nhánh thư viện',
                'ordering': ['library__name', 'name'],
            },
        ),
    ]
