# Generated by Django 6.0.3 on 2026-04-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_librarybranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarylocation',
            name='library_type',
            field=models.CharField(choices=[('public', 'Công cộng'), ('university', 'Đại học'), ('national', 'Quốc gia'), ('provincial', 'Tỉnh/Thành phố'), ('specialized', 'Chuyên ngành')], default='public', max_length=20, verbose_name='Loại thư viện'),
        ),
    ]
