# Generated by Django 4.2.30 on 2026-04-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_librarylocation_library_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='home_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ nhà'),
        ),
        migrations.AddField(
            model_name='reader',
            name='home_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ nhà'),
        ),
    ]
